### DISCUSSION TITLE
New kiosk idea using Google Home Hub

### DISCUSSION THREAD

**Discussion by poblabs** [poblabs/weewx-belchertown#806] [Ideas]
Just wanted to share something I came across today with using a Google Home Hub as a little kiosk. The way it works is using Home Assistant and creating a new dashboard view. The view type is 1 card, and the card is an iframe website card. Set the card to show your website. 

Then use the Home Assistant cast dashboard service to cast the dashboard. Example:

```
service: cast.show_lovelace_view
data:
  entity_id: media_player.pat_desk_nesthub
  dashboard_path: lovelace
  view_path: wx
```

I guess next steps would be to adjust the CSS to make it look good. 

In my spare time (which is almost none these days) 😄 

![image](https://user-images.githubusercontent.com/3484775/182449336-a93a165f-d846-4538-84bd-8b910c7c7cad.png)
